spring:
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
logging:
  level:
    org:
      hibernate: info
      hibernate.SQL: debug
      hibernate.cache: debug
app:
  scheduler:
    process-waiting-transactions:  '-'  ## disabled

